services:
  - type: web
    name: luxenest
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_luxenest && python manage.py import_forever_assets && python manage.py import_greatkart_assets"
    startCommand: "gunicorn luxenest.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: luxenest.settings.prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: SITE_URL
        value: "https://luxenest.onrender.com"
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        value: tonmoydeyrick@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "LuxeNest <tonmoydeyrick@gmail.com>"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
