from io import BytesIO


def money(value):
    return f"Rs. {value:,.2f}"


def render_invoice_pdf(order):
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except ImportError:
        return (
            b"%PDF-1.4\n"
            b"1 0 obj<<>>endobj\n"
            b"2 0 obj<</Length 64>>stream\nBT /F1 18 Tf 72 720 Td (LuxeNest invoice requires reportlab) Tj ET\nendstream endobj\n"
            b"trailer<<>>\n%%EOF"
        )

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=34, leftMargin=34, topMargin=30, bottomMargin=30)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Brand", parent=styles["Title"], textColor=colors.white, fontSize=30, leading=34))
    styles.add(ParagraphStyle(name="Muted", parent=styles["Normal"], textColor=colors.HexColor("#667085"), fontSize=9, leading=13))
    styles.add(ParagraphStyle(name="White", parent=styles["Normal"], textColor=colors.white, fontSize=10))
    styles.add(ParagraphStyle(name="SmallBold", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=9))
    styles.add(ParagraphStyle(name="Signature", parent=styles["Normal"], fontName="Times-Italic", textColor=colors.HexColor("#0B4AA2"), fontSize=18, leading=20, alignment=1))

    invoice_no = f"INV-{order.order_id}"
    customer = order.user.get_full_name() or order.user.username
    address = order.address
    address_text = f"{address.full_name}<br/>{address.line1}<br/>{address.line2 + '<br/>' if address.line2 else ''}{address.city}, {address.state} - {address.pincode}<br/>Phone: {address.phone}"

    header = Table(
        [
            [
                Paragraph("LuxeNest", styles["Brand"]),
                Paragraph(f"<b>Tax Invoice</b><br/>{invoice_no}<br/>Order: {order.order_id}<br/>Date: {order.created_at:%d %b %Y}", styles["White"]),
            ]
        ],
        colWidths=[305, 210],
    )
    header.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#062F69")),
                ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#062F69")),
                ("LINEBELOW", (0, 0), (-1, -1), 5, colors.HexColor("#D7A928")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 16),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]
        )
    )

    parties = Table(
        [
            [
                Paragraph("<b>Billed To</b><br/>" + customer + f"<br/>{order.user.email}", styles["Normal"]),
                Paragraph("<b>Shipping Address</b><br/>" + address_text, styles["Normal"]),
                Paragraph(f"<b>Payment</b><br/>{order.payment_method.upper()}<br/><b>Status</b><br/>{order.get_status_display()}", styles["Normal"]),
            ]
        ],
        colWidths=[170, 220, 125],
    )
    parties.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FBFF")),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#E5EAF3")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5EAF3")),
                ("PADDING", (0, 0), (-1, -1), 12),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    hero_note = Table(
        [[Paragraph("<b>Premium ecommerce invoice</b><br/>GST-ready billing, secure payment record, and digital invoice generated by LuxeNest.", styles["Muted"])]],
        colWidths=[515],
    )
    hero_note.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFF8DF")), ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#F0D77A")), ("PADDING", (0, 0), (-1, -1), 10)]))

    story = [
        header,
        Spacer(1, 10),
        hero_note,
        Spacer(1, 16),
        parties,
        Spacer(1, 18),
    ]
    rows = [["Product", "Variant", "Qty", "Unit Price", "GST", "Line Total"]]
    for item in order.items.all():
        rows.append(
            [
                Paragraph(item.product_name, styles["Normal"]),
                item.variant_label or "-",
                item.quantity,
                money(item.unit_price),
                f"{item.gst_rate}%",
                money(item.line_total),
            ]
        )
    rows.extend(
        [
            ["", "", "", "", "Subtotal", money(order.subtotal)],
            ["", "", "", "", "GST/Tax", money(order.tax)],
            ["", "", "", "", "Shipping", money(order.shipping)],
            ["", "", "", "", "Discount", f"- {money(order.discount)}"],
            ["", "", "", "", "Grand Total", money(order.total)],
        ]
    )
    table = Table(rows, colWidths=[175, 85, 40, 80, 55, 80], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#062F69")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5EAF3")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("BACKGROUND", (0, 1), (-1, -2), colors.HexColor("#FFFFFF")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -6), [colors.white, colors.HexColor("#F8FBFF")]),
                ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#FFF6D8")),
                ("FONTNAME", (4, -1), (-1, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (4, -1), (-1, -1), colors.HexColor("#0B4AA2")),
                ("ALIGN", (2, 1), (-1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 18))
    signature = Table(
        [
            [
                Paragraph("<b>Invoice assurance</b><br/>This invoice is system-generated from the confirmed LuxeNest order record.", styles["Muted"]),
                Paragraph("Tonmoy Dey<br/><font size='9' color='#667085'>CEO, LuxeNest</font>", styles["Signature"]),
            ]
        ],
        colWidths=[305, 210],
    )
    signature.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFFFF")),
                ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#E5EAF3")),
                ("LINEABOVE", (1, 0), (1, 0), 1.2, colors.HexColor("#D7A928")),
                ("PADDING", (0, 0), (-1, -1), 14),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    story.append(signature)
    story.append(Spacer(1, 14))
    note = Table(
        [
            [
                Paragraph("<b>Thank you for shopping with LuxeNest.</b><br/>For support, contact tonmoydeyrick@gmail.com. Keep this invoice for warranty, returns, and tax records.", styles["Muted"])
            ]
        ],
        colWidths=[515],
    )
    note.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FBFF")), ("BOX", (0, 0), (-1, -1), 0.6, colors.HexColor("#DCE7F5")), ("PADDING", (0, 0), (-1, -1), 12)]))
    story.append(note)
    doc.build(story)
    return buffer.getvalue()
