# Generated by Django 5.2.14 on 2026-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_external_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
